"""empty message

Revision ID: cc2d39034915
Revises: 
Create Date: 2020-04-21 17:18:38.298116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc2d39034915'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('exchange_rate')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'users', ['userid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_table('exchange_rate',
    sa.Column('from_currency', postgresql.ARRAY(sa.VARCHAR(length=3)), autoincrement=False, nullable=False),
    sa.Column('to_currency', postgresql.ARRAY(sa.VARCHAR(length=3)), autoincrement=False, nullable=False),
    sa.Column('exchange_rate', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('from_currency', 'to_currency', name='exchange_rate_pkey')
    )
    # ### end Alembic commands ###
