"""empty message

Revision ID: da5e244e3790
Revises: f9a98d49a26c
Create Date: 2020-04-26 19:21:13.672771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da5e244e3790'
down_revision = 'f9a98d49a26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('updated_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('from_currency', 'to_currency')
    )
    op.drop_table('exchange__rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange__rate',
    sa.Column('from_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('to_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('exchange_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('from_currency', 'to_currency', name='exchange__rate_pkey')
    )
    op.drop_table('exchange_rate')
    # ### end Alembic commands ###
