"""empty message

Revision ID: f9a98d49a26c
Revises: cc2d39034915
Create Date: 2020-04-26 19:10:05.057488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9a98d49a26c'
down_revision = 'cc2d39034915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange__rate',
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('updated_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('from_currency', 'to_currency')
    )
    op.drop_table('exchange_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('from_currency', postgresql.ARRAY(sa.VARCHAR(length=3)), autoincrement=False, nullable=False),
    sa.Column('to_currency', postgresql.ARRAY(sa.VARCHAR(length=3)), autoincrement=False, nullable=False),
    sa.Column('exchange_rate', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('from_currency', 'to_currency', name='exchange_rate_pkey')
    )
    op.drop_table('exchange__rate')
    # ### end Alembic commands ###
